/*
 * Code generated by Backengine
 *
 * https://backengine.dev
 */

import { createClientComponentClient } from "@supabase/auth-helpers-nextjs";
import type { Database } from "./types";

const supabase = createClientComponentClient<Database>();

export { supabase };
